author: BRICKMAKERS GmbH
title: BRICKMAKERS Hackathon
email: hackathon@brickmakers.de
description: >-
  Hier findet ihr in den kommenden Monaten Infos über unseren BRICKMAKERS Hackathon
baseurl: "/"
url: "htts://hackathon.brickmakers.de"
