author: BRICKMAKERS GmbH
title: BRICKMAKERS Hackathon
email: hackathon@brickmakers.de
description: >-
  Der Hackathon für deine Region – Online-Event am 09. & 10. Oktober 2020
baseurl: "/"
url: "htts://hackathon.brickmakers.de"
